language: java
jdk:
- openjdk8
before_deploy: mvn -B -DskipTests=true package
deploy:
  provider: releases
  api_key:
    secure: ti1fBFjb6+JkLk7C+GOb8cdyA3lDAYgywyWjlSnQQxxyNzlTueO+zE7MCHYQTUHPd/oVnjyjLlBop1fJ10vv7Mk553vzckwkvPnc1VmjSdQZQa0ytRtWPtLAZLLmiH/dYaySWb1LN/r6Pi1o/ebRpt13T8eJrkDjOliYLm3f0yiXzqRgW6bqRiRv8bpAuketRs8u2KDpaQePLgCM5tR3tpNKHfuad1s/ovKhNEhaeLVR46pY9jeoO0vQejwcSCwOCMfn4rg6VVRW5xPnDqJbKgdOePEO6IoWXXpJGMMTyGyLCgKLsq0y9BE9Mzuecj13VgGhgu2GKgqbxk/iPpAGOONSbKN4q0ryDoIdum/Qbv502jUklDyq8swaiuOIa8iT/fGyTtz6wZX9Mo3+TBkimTWcIDJPG5/9GEtsjayU/zFWcR0+1WBudeRZlZIHP6NxulWku3lrsRdh5AWeEybWtcVb6JaEOYSU5Mk6FZzF40+xRj0stNKizGhaN2oaExpPSACR5T36/MGGp1CM5k9vS89y3drnAOLsrD+uyBipFYmVM5ymYOeJ9UVq4vM2rF3iaqzKhEvrlc/RD/wbJ5ZV++p6xuReHJnVk1Oet4UecDxbAlXz2b+DiqnD9FXXEhfgQKiwXfY7GITekm6zOXzDIycE/bTJvepH8BNJrSYMjNo=
  file:
  - sonar-magik-plugin/target/sonar-magik-plugin-*.jar
  - magik-lint/target/magik-lint-*.jar
  - sslr-magik-toolkit/target/sslr-magik-toolkit-*.jar
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: StevenLooman/sonar-magik
    tags: true
